Add success button
xsoulspace/sheets_concat_excel_vba_macro pull request #3
Opened 2020-04-08 14:37 UTC by mixev

Close #1

2020-04-08 16:39 UTC, Arenukvern requested changes

2020-04-08 16:39 UTC, Arenukvern commented on mSheetConcat.bas
> +  Dim test as String
```suggestion
  
```

2020-04-08 16:39 UTC, Arenukvern commented on mSheetConcat.bas
> +  On Error GoTo ErrorHandler
Need to move to right after sub begins

2020-04-08 16:39 UTC, Arenukvern commented on mSheetConcat.bas
> +  Dim dangerText As String
Move declaration to error handler, it will be more readable

2020-04-10 12:21 UTC, mixev commented on mSheetConcat.bas
> +  On Error GoTo ErrorHandler
made fix position

2020-04-10 12:21 UTC, mixev commented on mSheetConcat.bas
> +  Dim dangerText As String
ready

2020-04-13 20:56 UTC, Arenukvern requested changes

2020-04-13 20:56 UTC, Arenukvern commented on mSheetConcat.bas
> +  Dim dangerText As String
@mixev  check it, I cannot see any changes 
Dim dangerText As String needs to be in error handler

2020-04-16 18:54 UTC, Arenukvern approved these changes
👍 💯

2020-06-02 21:46 UTC, merged